/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = [".avatar[_ngcontent-%COMP%] {\r\n    width: 80px;\r\n    height: 50px;\r\n    border-radius: 100%;    \r\n  }"];
export { styles as styles };
//# sourceMappingURL=github-followers.component.css.shim.ngstyle.js.map